#!/usr/bin/env bash
# Regenerate CHANGELOG.md from the repo's GitHub Releases (newest first).
# The release notes are the source of truth; this just collates them.
#
# Usage:  ./scripts/gen-changelog.sh [owner/repo]
# Requires: gh (authenticated).
set -euo pipefail

REPO="${1:-$(gh repo view --json nameWithOwner --jq .nameWithOwner)}"

{
  echo "# Changelog"
  echo
  echo "All notable changes to Kortex, collated from the [GitHub Releases]"
  echo "(https://github.com/$REPO/releases). This file is generated by"
  echo "\`scripts/gen-changelog.sh\` — edit releases, not this file."
  echo

  # Each release -> a section. Body headings (H2) are demoted to H3 so they nest
  # under the version heading. Releases come newest-first from the API.
  gh api "repos/$REPO/releases" --paginate --jq '
    .[]
    | "## \(.tag_name) — \((.published_at // .created_at)[0:10])\n\n"
      + ((.body // "" | gsub("\r";"") | gsub("^## ";"### ") | gsub("\n## ";"\n### "))
         | if . == "" then "_No notes._" else . end)
      + "\n"
  '
} > CHANGELOG.md

echo "Wrote CHANGELOG.md from $(gh api "repos/$REPO/releases" --jq 'length') release(s)."
